# Generated by Django 6.1.1 on 2026-09-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_otp_user_email_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
