# Generated by Django 6.1.1 on 2026-09-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='desired_job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='desired_salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='japanese_level',
            field=models.CharField(choices=[('not_required', 'Not specified'), ('n3', 'JLPT N3'), ('n2', 'JLPT N2'), ('n1', 'JLPT N1')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_workplace',
            field=models.CharField(choices=[('any', 'Any'), ('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='any', max_length=20),
        ),
    ]
